spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
server.servlet.context-path=/api
jwt.expiration=3000000
jwt.mysecret=fhjhdfkgjfkjgdkvhfhdfhgfdhxfdjgfjfgjghjhjkjhk
arrayOfEndpoints=/auth/**,/error,/swagger-ui/**,/swagger-ui.html
